TOWN_NAMES = [
    "Elderwood",
    "Shadowmere",
    "Willowbrook",
    "Ravencrest",
    "Windfall",
    "Silverdale",
    "Oakheart",
    "Bright Hollow",
    "Ironridge",
    "Mistvale",
    "Thornfield",
    "Goldhaven",
    "Redwater",
    "Stormwatch",
    "Greenhill",
    "Duskwood",
    "Brindleport",
    "Foxglove",
    "Ashenford",
    "Dragon’s Rest",
    "Briarwood",
    "Stonebridge",
    "Clearbrook",
    "Frostmere",
    "Highgarden",
    "Moonglade",
    "Seastone",
    "Winterhold",
    "Goldenleaf",
    "Whispering Pines",
    "Shadowgrove",
    "Sandspire",
    "Sunspire",
    "Lakeshire",
    "Deepwood",
    "Amberstone",
    "Crowhaven",
    "Bluehaven",
    "Silent Falls",
    "Everbrook",
    "Falcon's Reach",
    "Wolfwater",
    "Crimson Hollow",
    "Westmarch",
    "Ironwell",
    "Greenmarch",
    "Shady Grove",
    "Bouldercliff",
    "Hazelton",
    "Northpoint",
    "Woodmere",
    "Wyrm’s Rest",
    "Blackwater",
    "Silverwood",
    "Fallowfield",
    "Lunar Hollow",
    "Hightower",
    "Driftwood",
    "Havenwood",
    "Copperhill",
    "Emberhollow",
    "Thornwick",
    "Windmere",
    "Seabreeze",
    "Rivermouth",
    "Brightstone",
    "Meadowrun",
    "Stonefield",
    "Mossy Vale",
    "Eastwatch",
    "Burning Hollow",
    "Ravenwood",
    "Stonemoor",
    "Greendale",
    "Stormhaven",
    "Wishing Glen",
    "Falcon’s Hollow",
    "Nighthaven",
    "Frostfall",
    "Maplehold",
    "Drake’s Landing",
    "Red Hollow",
    "Glimmerwood",
    "Moonbright",
    "Fireshear",
    "Evershade",
    "Thunder Bluff",
    "Dunford",
    "Eagle’s Nest",
    "Brackenridge",
    "Brookmere",
    "Hawksgrove",
    "Blackthorn",
    "Sunford",
    "Silent Hollow",
    "Silverlake",
    "Stormspire",
    "Brightford",
    "Windridge",
    "Wintermere",
    "Crystal Falls",
    "Seastone Bay",
    "Brightvale",
    "Rockford",
    "Grovehill",
    "Ironwatch",
]
